name: Branch Deploy
on:
  repository_dispatch:
    types: rebuild

jobs:
  master-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Tar gz
        run: tar -zcvf app.tgz src
